spring:
  main:
    banner-mode: console

  datasource:
    url: jdbc:mysql://localhost:3306/bank?createDatabaseIfNotExist=true
    username: root
    password: Elina1980.

  jpa:
    generate-ddl: true
    show-sql: true

  liquibase:
    change-log: classpath:db.changelog/changelog-master.yaml
    enabled: true
    drop-first: true


server:
  port: 8080
